### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by dfreeman** [san650/ceibo#7]
I'm on a quest to start removing Bower dependencies from our apps where possible in the ultimate hope that once [Ember itself gets addonized](https://github.com/ember-cli/ember-cli/issues/4546) we'll be able stop using Bower entirely.

I went to go open a PR for ember-cli-page-object, but discovered Ceibo is currently only published to Bower. Would you consider publishing Ceibo to npm so that ember-cli-page-object could use it as a dependency from there instead of requiring Bower?

**Comment by jeradg** [comment]
@dfreeman: Yes, that's the plan. We intend to remove Bower dependencies from ember-cli-page-object, which will presumably mean that Ceibo will become an npm dependency.

**Comment by dfreeman** [comment]
Cool. Whenever the npm publish happens here, I'm happy to open up a PR with the changes for ember-cli-page-object – I've been [making](https://github.com/amiel/ember-data-url-templates/pull/18) [pretty good](https://github.com/csantero/ember-sinon/pull/35) [progress](https://github.com/yapplabs/ember-tether/pull/27) around the ecosystem 😄 .

**Comment by san650** [comment]
@dfreeman @jeradg I'll try to publish it today

**Comment by san650** [comment]
@dfreeman @jeradg Done. https://www.npmjs.com/package/ceibo
