### ISSUE TITLE
IE10 issues because of const?

### ISSUE THREAD

**Issue by toranb** [san650/ceibo#8]
I noticed today that const is used directly and not transpiled as I would have expected normally. Is it possible this is my fault on the ember-cli-build side of things or is this an oversight in ceibo?

if it is my fault - have you ever run into this before and if so what is a work around aside from forking?

https://github.com/san650/ceibo/blob/master/index.js#L124

thanks for maintaining such a great open source project!

**Comment by san650** [comment]
This is an oversight in Ceibo, sorry about that.

I'm using the library from projects where I transpile everything with babel so I didn't catch this error. Thanks for the error reporting.

**Comment by san650** [comment]
Fixed by #9

**Comment by toranb** [comment]
ah, no worries :) just wondered if it was only me for a minute. You mind doing a tag of v1.1.1 today if you get time?

**Comment by san650** [comment]
Sure, on it!

**Comment by toranb** [comment]
I owe you one! thank you !!!

**Comment by san650** [comment]
Done! https://www.npmjs.com/package/ceibo
